config/routes.rb
Rails.application.routes.draw do
  get 'bookmark/destroy'

  resources :topics

  root 'bookmarks#index'

  get 'welcome/index'

  get 'welcome/about'

  post :incoming, to: 'incoming#create'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :users, only: [:show, :update, :index]
  resources :bookmarks do
    resources :likes, only: [:create,:destroy]
  end

end

app/models/bookmark.rb
class Bookmark < ActiveRecord::Base

  belongs_to  :topic
  has_many    :likes, dependent: :destroy
  belongs_to  :user
  validates_with UrlValidator# on: :url
  validates :topic, presence: true
  validates :user, presence: true

  def liked?(current_user,bookmark)
    return false unless current_user
    Like.where(bookmark_id: bookmark.id, user_id: current_user.id).count > 0 ? "liked-#{bookmark.topic.color}":""
  end

end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  respond_to :html, :js

  def index
    @bookmarks = Bookmark.joins(:topic).order('topics.name').order('created_at DESC')
    @current_user = current_user
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    authorize @bookmark

    if @bookmark.destroy
      skip_annoying_flash = true
      @bookmark.topic.destroy if @bookmark.topic.bookmarks.count == 0
    else
      flash[:error] = "There was an error deleting the bookmark."
    end

    respond_with(@bookmark) do |format|
      format.html { redirect_to :back }
    end

  end
end

app/helpers/bookmark_helper.rb
module BookmarkHelper
end

app/views/bookmarks/_bookmark.html.erb
<!-- @bookmarks from topics/_topic.html.erb -->

<div class="item">

  <table class="table table-condensed table-curved bookmark-<%= bookmark.topic.color %> <%= bookmark.liked?(@current_user,bookmark) %>" id="bookmark-<%= bookmark.id %>">
    <tr>
      <td class="topic <%= bookmark.topic.color %>" id="topic-<%= bookmark.topic.id %>" colspan="2" >
        <%= link_to bookmark.topic.name, topic_path(bookmark.topic) %>
      </td>
    </tr>
    <% if bookmark.title %>
        <td class="heavy-title" colspan="2"><%= bookmark.title %></td>
    <% end %>
    <tr> <td class="url" colspan="2"><a href="<%= bookmark.url %>"><%= bookmark.url.truncate(30) %></a></td> </tr>

    <% if bookmark.description %>
        <tr> <td class="description" colspan="2"><%= bookmark.description %></td> </tr>
    <% end %>

    <% if bookmark.embed %>
        <tr> <td class="embed"     colspan="2"> <%= bookmark.embed.html_safe if bookmark.embed%> </td> </tr>
    <% elsif bookmark.thumbnail %>
        <tr>
          <td class="embed" colspan="2" >
            <img src="<%= bookmark.thumbnail if bookmark.thumbnail%>" alt="thumbnail fail"/>
          </td>
        </tr>
    <% end %>
    <tr>

      <td class="like-unlike-delete">
        <% if current_user %>
            <% if bookmark.liked?(@current_user,bookmark)['liked']%>
                <%= link_to "UNLIKE", bookmark_like_path( bookmark_id: bookmark.id, id:      current_user.id), id:"unlike-#{bookmark.id}",method: :delete, remote: true %>
                <%= link_to "LIKE",   bookmark_likes_path(bookmark_id: bookmark.id, user_id: current_user.id), class:"hidden", id:"like-#{bookmark.id}",method: :post,   remote: true %>
            <% else %>
                <%= link_to "UNLIKE", bookmark_like_path( bookmark_id: bookmark.id, id:      current_user.id), class:"hidden", id:"unlike-#{bookmark.id}",method: :delete, remote: true %>
                <%= link_to "LIKE",   bookmark_likes_path(bookmark_id: bookmark.id, user_id: current_user.id), id:"like-#{bookmark.id}",method: :post,   remote: true %>
            <% end %>
        <% end %>
      </td>

      <td class="like-unlike-delete">
        <% if current_user %>
            <% if policy(bookmark).destroy? %>
                <%= link_to "DELETE", bookmark_path(bookmark), method: :delete, remote: true %>
            <% end %>
        <% end %>
      </td>
    </tr>


  </table>

</div>

app/views/bookmarks/destroy.js.erb
<% if @bookmark.destroyed? %>
    // fade out the bookmark block itself
    $('#bookmark-' +<%= @bookmark.id %>).fadeOut();
    // decrement the badge counter on the topic bar
    $('a[href="/topics/<%= @bookmark.topic.id %>"]').find('span.total-bookmarks').text(<%= @bookmark.topic.bookmarks.count %>);
    <% if @bookmark.topic.bookmarks.count == 0 %>
        $('#topic-' +<%= @bookmark.topic.id %>).hide();
    <% end %>
    //  updating the badges in the nav bar
    $('#submissions').text(<%= current_user.bookmarks.count %>);
    $('#likes').text(<%= current_user.likes.count %>);
<% else %>
    $('#bookmark-' +<%= @bookmark.id %>).prepend("<div class='alert alert-error'><%= flash[:error] %></div>");
<% end %>

app/views/bookmarks/index.html.erb
<% if current_user %>
    <p class="headline headline-box">All Bookmarks</p>
<% else %>
    <p class="headline headline-box smaller">All Bookmarks - Sign In To Build Your Own Collection</p>
<% end %>


<div id="content" class="col-xs-10 col-xs-offset-1">
  <%= render @bookmarks %>
</div>