config/routes.rb
Rails.application.routes.draw do
  get 'bookmark/destroy'

  resources :topics

  root 'bookmarks#index'

  get 'welcome/index'

  get 'welcome/about'

  post :incoming, to: 'incoming#create'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :users, only: [:show, :update, :index]
  resources :bookmarks do
    resources :likes, only: [:create,:destroy]
  end

end

app/models/topic.rb
class Topic < ActiveRecord::Base
  belongs_to  :user
  has_many    :bookmarks

  validates :name, { :uniqueness => true }

  before_destroy :check_for_bookmarks

  default_scope {order('name')}

  def liked_bookmarks(cur_usr)
    return nil unless cur_usr
    liked_bookmark_ids = cur_usr.likes.pluck(:bookmark_id)
    bookmarks.where(id:liked_bookmark_ids).order('created_at DESC')
  end

  def check_for_bookmarks
    if bookmarks.any?
      errors[:base] << "cannot delete topic that still contains posts"
      return false
    end
  end

  def color_topic # distributes color-0 thru color-4 equally through all topics
    puts self.id
    "color-#{self.id % 5}"
  end

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: [:show, :edit, :update, :destroy]

  def index
    @topics = Topic.all
    @current_user = current_user
  end

  def show
    @topic = Topic.find(params[:id])
    @bookmarks = @topic.bookmarks
    @current_user = current_user
  end

  def new
    @topic = Topic.new
  end

  def edit
  end

  def create
    @topic = Topic.new(topic_params)

    respond_to do |format|
      if @topic.save
        format.html { redirect_to @topic, notice: 'Topic was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to :back, notice: 'Topic was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    if @topic.destroy
      redirect_to :back
    else
      redirect_to :back, notice: 'Topic cannot be destroyed. Still has bookmarks.'
    end
  end

  private

    def set_topic
      @topic = Topic.find(params[:id])
    end


    def topic_params
      params.require(:topic).permit(:name)
    end
end

app/views/topics/_form.html.erb
<%= form_for(@topic) do |f| %>
  <% if @topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
      <% @topic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/topics/_topic.html.erb
<!-- @liked_topics from users/_show.html.erb -->

<% visible_bookmarks = topic.liked_bookmarks(current_user) %>

<div class="topic-block" id="topic-<%= topic.id %>">
  <%= link_to topic do %>
      <h2><%= topic.name.titleize %></h2>
      <span class="badge pull-right liked-bookmarks"><%= visible_bookmarks.count %></span>
      <span class="badge pull-right total-bookmarks hidden"><%= topic.bookmarks.count %></span>
  <% end %>
</div>

<ul class="list-inline">
  <%= render visible_bookmarks %>
</ul>

<!-- @bookmarks to views/bookmarks/_bookmark.html.erb -->

app/views/topics/edit.html.erb
<h1>Editing topic</h1>

<%= render 'form' %>

<%= link_to 'Show', @topic %> |
<%= link_to 'Back', topics_path %>

app/views/topics/index.html.erb
<h3>All Topics</h3>

    <% @topics.each do |topic| %>
        <% visible_bookmarks = topic.liked_bookmarks(current_user) %>
        <!--<a href="<%#= topic_path(topic) %>" class="list-group-item"><%#= topic.name %><span class="badge"><%#= topic.bookmarks.count %></span></a>-->
        <div class="topic-block" id="topic-<%= topic.id %>">
          <%= link_to topic do %>
              <div class="topic-name">
                <%= topic.name.titleize if topic.name %>
                <span class="badge pull-right total-bookmarks"><%= topic.bookmarks.count %></span>
              </div>
          <% end %>

        </div>
        <div>
          <% if policy(topic).edit? %>
              <%= link_to 'EDIT', edit_topic_path(topic) %>
          <% end %>

          <% if policy(topic).destroy? %>
              <%= link_to 'DESTROY', topic, method: :delete, data: { confirm: 'Are you sure?' } %>
          <% end %>
        </div>


        <ul class="list-inline">
          <%= render topic.bookmarks %>
        </ul>


    <% end %>

app/views/topics/new.html.erb
<h1>New topic</h1>

<%= render 'form' %>

<%= link_to 'Back', topics_path %>

app/views/topics/show.html.erb
<p id="notice"><%= notice %></p>

<div id="content">
  <ul class="list-inline">
    <%= render @topic.bookmarks %>
  </ul>
  <%= link_to 'Back', bookmarks_path %>
</div>