config/routes.rb
Rails.application.routes.draw do
  get 'bookmark/destroy'

  resources :topics

  root 'bookmarks#index'

  get 'welcome/index'

  get 'welcome/about'

  post :incoming, to: 'incoming#create'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :users, only: [:show, :update, :index]
  resources :bookmarks do
    resources :likes, only: [:create,:destroy]
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bookmarking</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <link href='https://fonts.googleapis.com/css?family=Michroma' rel='stylesheet' type='text/css'>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
  <ul class="nav nav-tabs navbar-inverse navbar-fixed-top">
    <li><%#= link_to "Bloccit", root_path %></li>
    <li><%#= link_to "About", about_path %></li>
    <li><%= link_to "All Bookmarks", bookmarks_path %></li>
    <li>
      <%= mail_to "postmaster@app30409245.mailgun.org" do %>
          <p>Mail in a new URL <span class="glyphicon glyphicon-plus"></span></p>
      <% end %>
    </li>

    <li><%#= link_to "Popular", posts_path %></li>
    <li><%#= link_to "Users", users_path %></li>

    <div class="pull-right user-info">
      <% if current_user %>
          <%#= image_tag(current_user.avatar.tiny.url) if current_user.avatar? %>
          Hello <%= link_to (current_user.name || current_user.email), current_user %>!
          <span id="submissions"><%= current_user.bookmarks.count %></span> submissions and
          <span id="likes"><%= current_user.likes.count %></span> likes
          <%= link_to edit_user_registration_path, class: 'btn btn-primary btn-sm' do %>
              <span class="glyphicon glyphicon-user"></span>
          <% end %>
          <%= link_to destroy_user_session_path, method: :delete, class: 'btn btn-primary btn-sm' do %>
              <span class="glyphicon glyphicon-log-out"></span>
          <% end %>
      <% else %>
          <%= link_to "Sign In", new_user_session_path %> or
          <%= link_to "Sign Up", new_user_registration_path %>
      <% end %>
    </div><!-- end .pull-right user-info-->

  </ul><!-- end .nav nav-tabs-->

  <% if flash[:notice] %>
      <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:notice] %>
      </div>
  <% elsif flash[:error] %>
      <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:error] %>
      </div>
  <% elsif flash[:alert] %>
      <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:alert] %>
      </div>
  <% end %>

  <%#= yield %>
</div><!-- end .container-->
    <%= yield %>

</body>
</html>